image: python:3.8.5
services:
  - postgres:13
variables:
  POSTGRES_DB: "odoo"
  POSTGRES_USER: "odoo"
  POSTGRES_PASSWORD: "odoo"

stages:
  - test

code-check:
  stage: test
  script:
    - pip3 install pre-commit
    - pre-commit run --all-files
