image: python:3.8.5

stages:
  - test

code-check:
  except:
    - /^.*\.0$/
  stage: test
  variables:
    PRE_COMMIT_HOME: ${CI_PROJECT_DIR}/.cache/pre-commit
  cache:
    paths:
      - ${PRE_COMMIT_HOME}
  script:
    - pip3 install pre-commit
    - pre-commit run --all-files
