# Copyright (C) 2020 GlodoUK <https://www.glodo.uk>
# Copyright (C) 2010-2016 XCG Consulting <http://odoo.consulting>
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl).

import hashlib
import logging
from uuid import uuid4

import passlib

from odoo import SUPERUSER_ID, _, api, fields, models, tools
from odoo.exceptions import AccessDenied, ValidationError


_logger = logging.getLogger(__name__)


class ResUser(models.Model):
    _inherit = "res.users"

    def _ensure_saml_token_exists(self):
        # workaround for Odoo not seeing the newly created auth_saml.token on
        # the very first login
        model_token = self.env["auth_saml.token"].sudo()
        for record in self.sudo().filtered(lambda r: r.saml_ids):
            for provider in record.saml_ids:
                token = model_token.search(
                    [
                        ("user_id", "=", record.id),
                        ("saml_provider_id", "=", provider.saml_provider_id.id),
                    ]
                )
                if not token:
                    model_token.create(
                        {
                            "user_id": record.id,
                            "saml_provider_id": provider.saml_provider_id.id,
                        }
                    )
    @api.model
    def _allow_saml_and_password(self):
        """Can both SAML and local password auth methods can coexist."""
        return tools.str2bool(
            self.env["ir.config_parameter"]
            .sudo()
            .get_param("auth_saml.allow_saml_uid_and_internal_password", "True")
        )

    def _autoremove_password_if_saml(self):
        """Helper to remove password if it is forbidden for SAML users."""
        # TODO: Remove password only if settings requires to
        if self.env.context.get("auth_saml_no_autoremove_password"):
            return
        if self._allow_saml_and_password():
            return
        to_remove_password = self.filtered(
            lambda rec: rec.id != SUPERUSER_ID and rec.saml_ids and rec.password
        )
        if to_remove_password:

            to_remove_password.with_context(
                auth_saml_no_autoremove_password=True
            ).write({"password": self._autoremove_password_if_saml_gen_password()})

    @api.model_create_multi
    def create(self, vals_list):
        result = super().create(vals_list)
        result._autoremove_password_if_saml()
        result._ensure_saml_token_exists()
        return result

    def _saml_signup(self, vals):
        """
        Tawasta: Create user from vals

        :param vals: dict, user values
        :return: list
        """
        _logger.error("HERE saml_signup: vals: " + str(vals))
        return self.sudo().create(vals)

    def _auth_saml_signin(self, provider, validation, saml_response):
        saml_uid = validation["user_id"]
        prov = self.env["auth.saml.provider"].sudo().browse(provider)
        user = (
            self.env["res.users.saml"]
            .search(
                [("saml_uid", "=", saml_uid), ("saml_provider_id", "=", provider)],
                limit=1,
            )
            .user_id
        )
        if len(user) == 0:
            # User didn't exist, create
            _logger.warning("User didn't exist, lets create one?!")
            vals = validation.get("mapped_attrs")
            if not vals.get("login"):
                # If no login attribute defined, use autogenerated
                vals["login"] = "saml-{}".format(uuid4())

            vals["groups_id"] = [(6, 0, prov.group_ids.ids)]
            user = self._saml_signup(vals)
            user.write(
                {
                    "saml_ids": [
                        (
                            0,
                            0,
                            {
                                "saml_provider_id": provider,
                                "saml_uid": saml_uid,
                            },
                        )
                    ]
                }
            )
        else:
            token_osv = self.env["auth_saml.token"]
            token_ids = token_osv.search(
                [("saml_provider_id", "=", provider), ("user_id", "=", user.id)]
            )
            # TODO: Save session info to somewhere - tokens -model?
            name_id = validation.get("name_id")
            if token_ids:
                token_ids.write(
                    {
                        "saml_access_token": saml_response,
                        "saml_name_id": name_id,
                    }
                )
            else:
                _logger.info("Creating auth_saml.token")
                token_ids = token_osv.create(
                    {
                        "saml_access_token": saml_response,
                        "saml_provider_id": provider,
                        "user_id": user.id,
                        "saml_name_id": name_id,
                    }
                )

        return super()._auth_saml_signin(provider, validation, saml_response)