name: Open PR from prod to dev
permissions:
  contents: write
  pull-requests: write

on:
  push:
    branches:
      - 17.0

jobs:
  open-pr-to-dev:
    uses: tawasta/github-workflows/.github/workflows/open-pr-to-dev.yml@main
    with:
      target_branch: 17.0-dev
